mdadm: add attribute nonstring for signature
It reports building error in f42:
error: initializer-string for array of ‘unsigned char’ truncates NULL
terminator but destination lacks ‘nonstring’ attribute (5 chars into 4
available) [-Werror=unterminated-string-initialization]

Signed-off-by: Xiao Ni <xni@redhat.com>
(cherry picked from commit d4bfbc4bab7aeeb89cf679855851d47940baebb4)